"""
Bilingual Report Labels (English/Khmer)
"""

REPORT_LABELS = {
    # Header
    'company_name': '☀️ KHSolar',
    'company_subtitle': 'Professional Solar System Design & Analysis / ការរចនាប្រព័ន្ធថាមពលពន្លឺព្រះអាទិត្យ និងការវិភាគវិជ្ជាជីវៈ',
    'report_title': 'SOLAR SYSTEM ANALYSIS REPORT / របាយការណ៍ការវិភាគប្រព័ន្ធថាមពលពន្លឺព្រះអាទិត្យ',
    'report_generated': 'Report Generated / របាយការណ៍បានបង្កើត',
    
    # Customer Information
    'customer_info': 'Customer Information / ព័ត៌មានអតិថិជន',
    'customer_name': 'Customer Name / ឈ្មោះអតិថិជន',
    'company': 'Company / ក្រុមហ៊ុន',
    'phone': 'Phone / លេខទូរស័ព្ទ',
    'email': 'Email / អ៊ីមែល',
    'address': 'Address / អាសយដ្ឋាន',
    'individual': 'Individual / បុគ្គល',
    
    # System Configuration
    'system_config': 'System Configuration / ការកំណត់រចនាសម្ព័ន្ធប្រព័ន្ធ',
    'parameter': 'Parameter / ប៉ារ៉ាម៉ែត្រ',
    'value': 'Value / តម្លៃ',
    'unit': 'Unit / ឯកតា',
    'location': 'Location / តំបន់',
    'pv_capacity': 'PV Capacity / សមត្ថភាពផ្ទាំងសូឡា',
    'battery_capacity': 'Battery Capacity / សមត្ថភាពថ្ម',
    'inverter_power': 'Inverter Power / ថាមពលឧបករណ៍បំប្លែង',
    'num_devices': 'Number of Devices / ចំនួនឧបករណ៍',
    'system_type': 'System Type / ប្រភេទប្រព័ន្ធ',
    'grid_tied_battery': 'Grid-Tied with Battery Backup / ភ្ជាប់បណ្តាញជាមួយបម្រុងថ្ម',
    'labor_cost': 'Labor Cost / ថ្លៃដៃ',
    'support_materials': 'Support Materials / សម្ភារៈជំនួយ',
    
    # Cost Breakdown
    'cost_breakdown': 'System Cost Breakdown / ការបែងចែកថ្លៃដើមប្រព័ន្ធ',
    'cost_component': 'Cost Component / សមាសធាតុថ្លៃដើម',
    'amount': 'Amount / ចំនួនទឹកប្រាក់',
    'percentage': 'Percentage / ភាគរយ',
    'equipment': 'Equipment (Panels, Battery, Inverter) / ឧបករណ៍ (ផ្ទាំងសូឡា, ថ្ម, ឧបករណ៍បំប្លែង)',
    'labor_system': 'Labor Cost / ថ្លៃដៃ',
    'support_installation': 'Support Materials & Installation / សម្ភារៈជំនួយ និងការដំឡើង',
    'total_system_cost': 'Total System Cost / តម្លៃប្រព័ន្ធសរុប',
    'system_5kw': '≤5kW system / ប្រព័ន្ធ ≤5kW',
    'system_above_5kw': '>5kW system / ប្រព័ន្ធ >5kW',
    
    # Financial Analysis
    'financial_analysis': 'Financial Analysis & ROI / ការវិភាគហិរញ្ញវត្ថុ និង ROI',
    'metric': 'Metric / ប្រភេទ',
    'details': 'Details / ព័ត៌មានលម្អិត',
    'total_investment': 'Total System Investment / ការវិនិយោគប្រព័ន្ធសរុប',
    'complete_installation': 'Complete installation cost / ថ្លៃដំឡើងពេញលេញ',
    'monthly_savings': 'Monthly Savings / ការសន្សំប្រចាំខែ',
    'electricity_reduction': 'Electricity bill reduction / កាត់បន្ថយវិក្កយប័ត្រអគ្គិសនី',
    'annual_savings': 'Annual Savings / ការសន្សំប្រចាំឆ្នាំ',
    'year1_savings': 'Year 1 savings / ការសន្សំឆ្នាំទី១',
    'payback_period': 'Payback Period / រយៈពេលសងត្រលប់',
    'breakeven_point': 'Break-even point / ចំណុចទ្រព្យសមតុល្យ',
    'roi': 'Return on Investment / ការត្រលប់មកវិញនៃការវិនិយោគ',
    'over_25years': 'Over 25 years / រយៈពេល ២៥ ឆ្នាំ',
    'lifetime_savings': 'Lifetime Savings / ការសន្សំអស់មួយជីវិត',
    'total_25years': '25-year total savings / ការសន្សំសរុប ២៥ ឆ្នាំ',
    'co2_reduction': 'CO2 Reduction / ការកាត់បន្ថយ CO2',
    'environmental_impact': 'Environmental impact / ផលប៉ះពាល់បរិស្ថាន',
    
    # Energy Analysis
    'energy_analysis': 'Energy Production & Consumption Analysis / ការវិភាគផលិតកម្ម និងការប្រើប្រាស់ថាមពល',
    'daily': 'Daily / ប្រចាំថ្ងៃ',
    'monthly': 'Monthly / ប្រចាំខែ',
    'annual_est': 'Annual (Est.) / ប្រចាំឆ្នាំ (ប៉ាន់ស្មាន)',
    'solar_generation': 'Solar PV Generation / ការផលិតថាមពលពន្លឺព្រះអាទិត្យ',
    'total_consumption': 'Total Energy Consumption / ការប្រើប្រាស់ថាមពលសរុប',
    'grid_import': 'Grid Import (Buy) / ទិញពីបណ្តាញ',
    'grid_export': 'Grid Export (Sell) / លក់ទៅបណ្តាញ',
    'self_sufficiency': 'Energy Self-Sufficiency / ភាពគ្រប់គ្រាន់ដោយខ្លួនឯង',
    
    # Device Inventory
    'device_inventory': 'Complete Device Inventory / បញ្ជីឧបករណ៍ពេញលេញ',
    'total_devices': 'Total Devices / ឧបករណ៍សរុប',
    'total_power': 'Total Power / ថាមពលសរុប',
    'daily_consumption': 'Daily Consumption / ការប្រើប្រាស់ប្រចាំថ្ងៃ',
    'priority_devices': 'Priority Devices / ឧបករណ៍អាទិភាព',
    'device_name': 'Device Name / ឈ្មោះឧបករណ៍',
    'power_w': 'Power (W) / ថាមពល (វ៉ាត់)',
    'hours_day': 'Hours/Day / ម៉ោង/ថ្ងៃ',
    'daily_energy': 'Daily Energy / ថាមពលប្រចាំថ្ងៃ',
    'type': 'Type / ប្រភេទ',
    'priority': 'Priority / អាទិភាព',
    
    # Footer
    'footer_text': 'This report is generated by KHSolar Professional Solar Design Software / របាយការណ៍នេះត្រូវបានបង្កើតដោយ KHSolar ​ソフトウェアការរចនាប្រព័ន្ធថាមពលពន្លឺព្រះអាទិត្យវិជ្ជាជីវៈ',
    'contact_support': 'For questions or support, please contact your solar consultant / សម្រាប់សំណួរ ឬការគាំទ្រ សូមទាក់ទងទៅអ្នកប្រឹក្សាថាមពលពន្លឺព្រះអាទិត្យរបស់អ្នក',
    'report_id': 'Report ID / លេខសម្គាល់របាយការណ៍',
}
