"""
Dual Language Report Templates (English/Khmer)
For KHSolar Telegram Bot
"""

CONTACT_INFO_EN = """
📞 <b>Contact Us - Free Consultation</b>
━━━━━━━━━━━━━━━━━━━━
📱 Call: 0888836588
💬 Telegram: @chhanycls
🕐 Available anytime for free consultation!
"""

CONTACT_INFO_KH = """
📞 <b>ទំនាក់ទំនងពួកយើង - ពិគ្រោះយោបល់ឥតគិតថ្លៃ</b>
━━━━━━━━━━━━━━━━━━━━
📱 ទូរស័ព្ទ: 0888836588
💬 តេឡេក្រាម: @chhanycls
🕐 អាចទំនាក់ទំនងបានគ្រប់ពេល ពិគ្រោះយោបល់ឥតគិតថ្លៃ!
"""

def format_report_english(data):
    """Format report in English"""
    
    backup_hours = 0
    if data.get('battery_kwh', 0) > 0 and data.get('daily_kwh', 0) > 0:
        backup_hours = (data['battery_kwh'] * 0.8) / (data['daily_kwh'] / 24)
    
    report = f"""
🌞 <b>KHSolar System Report</b>

━━━━━━━━━━━━━━━━━━━━
👤 <b>Customer Information</b>
━━━━━━━━━━━━━━━━━━━━

<b>Name:</b> {data.get('customer_name', 'N/A')}
<b>Phone:</b> {data.get('phone', 'N/A')}
<b>Location:</b> {data.get('address', 'Cambodia')}

━━━━━━━━━━━━━━━━━━━━
⚡ <b>System Overview</b>
━━━━━━━━━━━━━━━━━━━━

<b>Monthly Consumption:</b> {data.get('monthly_kwh', 0):.0f} kWh
<b>Daily Average:</b> {data.get('daily_kwh', 0):.1f} kWh
<b>System Type:</b> {data.get('system_type', 'N/A')}

━━━━━━━━━━━━━━━━━━━━
☀️ <b>Solar Panels</b>
━━━━━━━━━━━━━━━━━━━━

<b>Quantity:</b> {data.get('num_panels', 0)} panels
<b>Power per Panel:</b> {data.get('panel_wattage', 0)}W
<b>Total Capacity:</b> {data.get('pv_kw', 0):.2f} kW
<b>Monthly Generation:</b> ~{data.get('pv_generation', 0):.0f} kWh

━━━━━━━━━━━━━━━━━━━━
🔋 <b>Battery Storage</b>
━━━━━━━━━━━━━━━━━━━━

<b>Total Capacity:</b> {data.get('battery_kwh', 0):.2f} kWh
<b>Usable Capacity:</b> {data.get('battery_kwh', 0) * 0.8:.2f} kWh (80% DoD)
<b>Backup Time:</b> ~{backup_hours:.1f} hours
<b>Units:</b> {data.get('num_batteries', 0)}

━━━━━━━━━━━━━━━━━━━━
⚡ <b>Inverter</b>
━━━━━━━━━━━━━━━━━━━━

<b>Power Rating:</b> {data.get('inverter_kw', 0):.1f} kW
<b>Type:</b> {data.get('system_type', 'N/A')}
<b>Efficiency:</b> 97%

━━━━━━━━━━━━━━━━━━━━
💰 <b>Investment Details</b>
━━━━━━━━━━━━━━━━━━━━

<b>💎 TOTAL SYSTEM PRICE</b>
<b>${data.get('total_price', 0):,.2f}</b>

<b>Monthly Savings:</b> ${data.get('monthly_savings', 0):,.2f}
<b>Annual Savings:</b> ${data.get('annual_savings', 0):,.2f}
<b>Payback Period:</b> {data.get('payback_years', 0):.1f} years

⚠️ <b>Note:</b> The total price can be less or more, this is generated by software. We highly recommend you to call or message for real prices and consultation.

━━━━━━━━━━━━━━━━━━━━
📊 <b>System Benefits</b>
━━━━━━━━━━━━━━━━━━━━

✅ Reduce electricity bills by ~{(data.get('annual_savings', 0) / (data.get('monthly_kwh', 1) * 12 * 0.20)) * 100:.0f}%
✅ Clean, renewable energy
✅ Energy independence
✅ Increase property value
✅ 25+ year solar panel lifespan

━━━━━━━━━━━━━━━━━━━━

{CONTACT_INFO_EN}

<i>Generated by KHSolar System Designer</i>
<i>Report Date: {data.get('date', 'N/A')}</i>
"""
    return report


def format_report_khmer(data):
    """Format report in Khmer"""
    
    backup_hours = 0
    if data.get('battery_kwh', 0) > 0 and data.get('daily_kwh', 0) > 0:
        backup_hours = (data['battery_kwh'] * 0.8) / (data['daily_kwh'] / 24)
    
    report = f"""
🌞 <b>របាយការណ៍ប្រព័ន្ធថាមពលព្រះអាទិត្យ KHSolar</b>

━━━━━━━━━━━━━━━━━━━━
👤 <b>ព័ត៌មានអតិថិជន</b>
━━━━━━━━━━━━━━━━━━━━

<b>ឈ្មោះ:</b> {data.get('customer_name', 'N/A')}
<b>លេខទូរស័ព្ទ:</b> {data.get('phone', 'N/A')}
<b>ទីតាំង:</b> {data.get('address', 'កម្ពុជា')}

━━━━━━━━━━━━━━━━━━━━
⚡ <b>ទិដ្ឋភាពទូទៅនៃប្រព័ន្ធ</b>
━━━━━━━━━━━━━━━━━━━━

<b>ការប្រើប្រាស់ប្រចាំខែ:</b> {data.get('monthly_kwh', 0):.0f} kWh
<b>មធ្យមប្រចាំថ្ងៃ:</b> {data.get('daily_kwh', 0):.1f} kWh
<b>ប្រភេទប្រព័ន្ធ:</b> {data.get('system_type', 'N/A')}

━━━━━━━━━━━━━━━━━━━━
☀️ <b>បន្ទះថាមពលព្រះអាទិត្យ</b>
━━━━━━━━━━━━━━━━━━━━

<b>បរិមាណ:</b> {data.get('num_panels', 0)} បន្ទះ
<b>កម្លាំងក្នុងមួយបន្ទះ:</b> {data.get('panel_wattage', 0)}W
<b>សមត្ថភាពសរុប:</b> {data.get('pv_kw', 0):.2f} kW
<b>ការផលិតប្រចាំខែ:</b> ~{data.get('pv_generation', 0):.0f} kWh

━━━━━━━━━━━━━━━━━━━━
🔋 <b>ប្រព័ន្ធផ្ទុកថាមពល (Battery)</b>
━━━━━━━━━━━━━━━━━━━━

<b>សមត្ថភាពសរុប:</b> {data.get('battery_kwh', 0):.2f} kWh
<b>សមត្ថភាពអាចប្រើបាន:</b> {data.get('battery_kwh', 0) * 0.8:.2f} kWh (80% DoD)
<b>ពេលវេលាបម្រុងទុក:</b> ~{backup_hours:.1f} ម៉ោង
<b>ចំនួនគ្រឿង:</b> {data.get('num_batteries', 0)}

━━━━━━━━━━━━━━━━━━━━
⚡ <b>ឧបករណ៍បំលែងថាមពល (Inverter)</b>
━━━━━━━━━━━━━━━━━━━━

<b>កម្លាំង:</b> {data.get('inverter_kw', 0):.1f} kW
<b>ប្រភេទ:</b> {data.get('system_type', 'N/A')}
<b>ប្រសិទ្ធភាព:</b> 97%

━━━━━━━━━━━━━━━━━━━━
💰 <b>ព័ត៌មានការវិនិយោគ</b>
━━━━━━━━━━━━━━━━━━━━

<b>💎 តម្លៃប្រព័ន្ធសរុប</b>
<b>${data.get('total_price', 0):,.2f}</b>

<b>សន្សំប្រចាំខែ:</b> ${data.get('monthly_savings', 0):,.2f}
<b>សន្សំប្រចាំឆ្នាំ:</b> ${data.get('annual_savings', 0):,.2f}
<b>រយៈពេលសងត្រឡប់:</b> {data.get('payback_years', 0):.1f} ឆ្នាំ

⚠️ <b>ចំណាំ:</b> តម្លៃសរុបអាចតិចឬច្រើន នេះបង្កើតដោយកម្មវិធី។ យើងសូមណែនាំឱ្យអ្នកទូរស័ព្ទ ឬផ្ញើសារសម្រាប់តម្លៃពិតប្រាកដ និងការប្រឹក្សា។

━━━━━━━━━━━━━━━━━━━━
📊 <b>អត្ថប្រយោជន៍ប្រព័ន្ធ</b>
━━━━━━━━━━━━━━━━━━━━

✅ បន្ថយការចំណាយអគ្គិសនី ~{(data.get('annual_savings', 0) / (data.get('monthly_kwh', 1) * 12 * 0.20)) * 100:.0f}%
✅ ថាមពលស្អាត និងបរិស្ថាន
✅ ឯករាជ្យភាពថាមពល
✅ បង្កើនតម្លៃអចលនទ្រព្យ
✅ បន្ទះថាមពលអាចប្រើបានជាង 25 ឆ្នាំ

━━━━━━━━━━━━━━━━━━━━

{CONTACT_INFO_KH}

<i>បង្កើតដោយ KHSolar System Designer</i>
<i>កាលបរិច្ឆេទរបាយការណ៍: {data.get('date', 'N/A')}</i>
"""
    return report


def format_report_bilingual(data):
    """Format report with both English and Khmer"""
    
    backup_hours = 0
    if data.get('battery_kwh', 0) > 0 and data.get('daily_kwh', 0) > 0:
        backup_hours = (data['battery_kwh'] * 0.8) / (data['daily_kwh'] / 24)
    
    report = f"""
🌞 <b>KHSolar System Report | របាយការណ៍ប្រព័ន្ធថាមពលព្រះអាទិត្យ</b>

━━━━━━━━━━━━━━━━━━━━
👤 <b>Customer Information | ព័ត៌មានអតិថិជន</b>
━━━━━━━━━━━━━━━━━━━━

<b>Name | ឈ្មោះ:</b> {data.get('customer_name', 'N/A')}
<b>Phone | លេខទូរស័ព្ទ:</b> {data.get('phone', 'N/A')}
<b>Location | ទីតាំង:</b> {data.get('address', 'Cambodia | កម្ពុជា')}

━━━━━━━━━━━━━━━━━━━━
⚡ <b>System Overview | ទិដ្ឋភាពទូទៅ</b>
━━━━━━━━━━━━━━━━━━━━

<b>Monthly | ប្រចាំខែ:</b> {data.get('monthly_kwh', 0):.0f} kWh
<b>Daily | ប្រចាំថ្ងៃ:</b> {data.get('daily_kwh', 0):.1f} kWh
<b>Type | ប្រភេទ:</b> {data.get('system_type', 'N/A')}

━━━━━━━━━━━━━━━━━━━━
☀️ <b>Solar Panels | បន្ទះថាមពលព្រះអាទិត្យ</b>
━━━━━━━━━━━━━━━━━━━━

<b>Quantity | បរិមាណ:</b> {data.get('num_panels', 0)} panels | បន្ទះ
<b>Power | កម្លាំង:</b> {data.get('panel_wattage', 0)}W per panel | ក្នុងមួយបន្ទះ
<b>Total Capacity | សមត្ថភាព:</b> {data.get('pv_kw', 0):.2f} kW
<b>Monthly Generation | ការផលិត:</b> ~{data.get('pv_generation', 0):.0f} kWh

━━━━━━━━━━━━━━━━━━━━
🔋 <b>Battery | ប្រព័ន្ធផ្ទុកថាមពល</b>
━━━━━━━━━━━━━━━━━━━━

<b>Capacity | សមត្ថភាព:</b> {data.get('battery_kwh', 0):.2f} kWh
<b>Usable | អាចប្រើបាន:</b> {data.get('battery_kwh', 0) * 0.8:.2f} kWh (80% DoD)
<b>Backup | បម្រុងទុក:</b> ~{backup_hours:.1f} hours | ម៉ោង
<b>Units | ចំនួន:</b> {data.get('num_batteries', 0)}

━━━━━━━━━━━━━━━━━━━━
⚡ <b>Inverter | ឧបករណ៍បំលែងថាមពល</b>
━━━━━━━━━━━━━━━━━━━━

<b>Power | កម្លាំង:</b> {data.get('inverter_kw', 0):.1f} kW
<b>Type | ប្រភេទ:</b> {data.get('system_type', 'N/A')}
<b>Efficiency | ប្រសិទ្ធភាព:</b> 97%

━━━━━━━━━━━━━━━━━━━━
💰 <b>Investment | ការវិនិយោគ</b>
━━━━━━━━━━━━━━━━━━━━

<b>💎 TOTAL PRICE | តម្លៃសរុប</b>
<b>${data.get('total_price', 0):,.2f}</b>

<b>Monthly Savings | សន្សំប្រចាំខែ:</b> ${data.get('monthly_savings', 0):,.2f}
<b>Annual Savings | សន្សំប្រចាំឆ្នាំ:</b> ${data.get('annual_savings', 0):,.2f}
<b>Payback Period | រយៈពេលសងត្រឡប់:</b> {data.get('payback_years', 0):.1f} years | ឆ្នាំ

⚠️ <b>Note | ចំណាំ:</b> The total price can be less or more, this is generated by software. We highly recommend you to call or message for real prices and consultation. | តម្លៃសរុបអាចតិចឬច្រើន នេះបង្កើតដោយកម្មវិធី។ យើងសូមណែនាំឱ្យអ្នកទូរស័ព្ទ ឬផ្ញើសារសម្រាប់តម្លៃពិតប្រាកដ និងការប្រឹក្សា។

━━━━━━━━━━━━━━━━━━━━
📊 <b>Benefits | អត្ថប្រយោជន៍</b>
━━━━━━━━━━━━━━━━━━━━

✅ Reduce bills by | បន្ថយថ្លៃ ~{(data.get('annual_savings', 0) / (data.get('monthly_kwh', 1) * 12 * 0.20)) * 100:.0f}%
✅ Clean energy | ថាមពលស្អាត
✅ Energy independence | ឯករាជ្យភាពថាមពល
✅ 25+ years lifespan | ប្រើបានជាង 25 ឆ្នាំ

━━━━━━━━━━━━━━━━━━━━

{CONTACT_INFO_EN}

{CONTACT_INFO_KH}

<i>Generated by KHSolar System Designer</i>
<i>Report Date | កាលបរិច្ឆេទ: {data.get('date', 'N/A')}</i>
"""
    return report
